Step 1 for building FV3 regional preprocessing on Cheyenne
Currently only fre-nctools builds successfully

 - Modify "build_regional" script to take the platform as a
   command-line argument
 - Modify "build_fre-nctools.sh" and "machine-setup.sh" to allow the
   platform as an argument, rather than the ugly "look for some
   directory that exists" method of determining which machine we are
   on. This still preserves back compatiblity so behavior on other
   platforms should remain unchanged, but this is something we should
    REALLY consider eliminating
 - Add appropriate Cheyenne make, env, and module files

diff --git a/regional/build_regional b/regional/build_regional
--- a/regional/build_regional
+++ b/regional/build_regional
@@ -1,14 +1,19 @@
 #!/bin/bash
 set -eux
 
+if [ $# -eq 0 ] ; then
+    echo "ERROR: You must provide the platform as a command-line argument"
+    exit 1
+fi
+
 SITE=${1}
 
 FV3GFS_DIR=$( pwd )/..
 
 cd ${FV3GFS_DIR}/sorc
-./build_fre-nctools.sh >& out.build_fre-nctools
-./build_orog.sh ${SITE} >& out.build_orog
-./build_chgres.sh      >& out.build_chgres
+./build_fre-nctools.sh ${SITE} >& out.build_fre-nctools
+./build_orog.sh ${SITE}        >& out.build_orog
+./build_chgres.sh ${SITE}      >& out.build_chgres
 
 
 cd ${FV3GFS_DIR}/../NEMSfv3gfs/tests
@@ -32,6 +37,10 @@ elif [ ${SITE} == "wcoss_cray" ]; then
 elif [ ${SITE} == "odin" ]; then
 
     ln -fs /scratch/ywang/test_runs/C768_nest/fv3-fix fix_am
+
+elif [ ${SITE} == "cheyenne" ]; then
+
+    ln -sf /glade/p/ral/jntp/GMTB/FV3GFS_V1_RELEASE/fix/fix_am/ fix_am
 
 else
     echo "Unknown site " ${SITE}
