change file names of forecast, post, aqm_ics, and aqm_lbcs for J-jobs and exscripts

diff --git a/jobs/JAQM_POINT_SOURCE b/jobs/JAQM_POINT_SOURCE
--- a/jobs/JAQM_POINT_SOURCE
+++ b/jobs/JAQM_POINT_SOURCE
@@ -7,7 +7,9 @@ set -xue
 #-----------------------------------------------------------------------
 # Source the variable definitions file and the bash utility functions.
 #-----------------------------------------------------------------------
-. $USHdir/source_util_funcs.sh
+export USHaqm=${USHaqm:-${HOMEaqm}/ush}
+
+. $USHaqm/source_util_funcs.sh
 source_config_for_task "task_run_fcst|cpl_aqm_parm|task_point_source" ${GLOBAL_VAR_DEFNS_FP}
 
 export DATAROOT="${DATAROOT:-${DATAROOT_dfv}}"
@@ -17,13 +19,14 @@ mkdir -p ${DATA}
 cd ${DATA}
 
 export cycle=${cycle:-t${cyc}z}
+export CDATE=${PDY}${cyc}
+
 setpdy.sh
 . ./PDY
 
-. $USHdir/job_preamble.sh
+. $USHaqm/job_preamble.sh
 
 export COMINemispt="${COMINemispt:-${COMIN}/emission/pt}"
-export USHaqm=${USHaqm:-${HOMEaqm}/ush}
 export EXECaqm=${EXECaqm:-${HOMEaqm}/exec}
 export PARMaqm=${PARMaqm:-${HOMEaqm}/parm}
 export FIXaqm=${FIXaqm:-${HOMEaqm}/fix}
@@ -39,7 +42,7 @@ export COMOUT="${COMOUT:-$(compath.py -o ${NET}/${model_ver}/${RUN}.${PDY}/${cyc
 # Save current shell options (in a global array).  Then set new options
 # for this script/function.
 #-----------------------------------------------------------------------
-{ save_shell_opts; . $USHdir/preamble.sh; } > /dev/null 2>&1
+{ save_shell_opts; . $USHaqm/preamble.sh; } > /dev/null 2>&1
 #-----------------------------------------------------------------------
 #
 # Get the full path to the file in which this script/function is located 
@@ -80,20 +83,26 @@ DATA="${DATA:-${COMIN}${SLASH_ENSMEM_SUBDIR}/tmp_POINT_SOURCE}"
 #
 #
 #-----------------------------------------------------------------------
-#
 # Call the ex-script for this J-job.
-#
 #-----------------------------------------------------------------------
 #
-$SCRIPTSdir/exaqm_point_source.sh || \
-print_err_msg_exit "\
-Call to ex-script corresponding to J-job \"${scrfunc_fn}\" failed."
+startmsg
+${HOMEaqm}/scripts/exaqm_point_source.sh
+export err=$?; err_chk
+#$SCRIPTSdir/exaqm_point_source.sh || \
+#print_err_msg_exit "\
+#Call to ex-script corresponding to J-job \"${scrfunc_fn}\" failed."
 #
-#-----------------------------------------------------------------------
-# Run job postamble.
-#-----------------------------------------------------------------------
-#
-job_postamble
+if [ "${KEEPDATA}" = "FALSE" ]; then
+   cd ${DATAROOT}
+   rm -rf $DATA
+fi
+# Print exit message
+print_info_msg "
+========================================================================
+Exiting script:  \"${scrfunc_fn}\"
+In directory:    \"${scrfunc_dir}\"
+========================================================================"
 #
 #-----------------------------------------------------------------------
 #
